name: travel_booking_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 
  flutter_spinkit: ^5.2.0
  intl: ^0.17.0
  cupertino_icons: ^0.1.2
  google_fonts: 
  shared_preferences: 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/flight1.json
      - assets/flight2.json
      - assets/images/
      - assets/images/hotel/hotel1.jpg      
      - assets/images/hotel/hotel2.jpg
      - assets/images/hotel/hotel3.jpg
      - assets/images/hotel/hotel4.jpg
      - assets/images/hotel/hotel5.jpg
      - assets/images/hotel/hotel6.jpg
      - assets/images/hotel/hotel8.jpg
      - assets/images/hotel/hotel8.jpg
      - assets/images/hotel/hotel9.jpg     
      - assets/images/hotel/hotel10.jpg
      - assets/images/hotel/hotel11.jpg
      - assets/images/hotel/hotel12.jpg



